//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cineflex.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ApplicationTranslation {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ApplicationTranslation() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cineflex.Resources.ApplicationTranslation", typeof(ApplicationTranslation).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string ConfirmDialog_Cancel {
            get {
                return ResourceManager.GetString("ConfirmDialog_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string ConfirmDialog_Confirm {
            get {
                return ResourceManager.GetString("ConfirmDialog_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to proceed?.
        /// </summary>
        public static string ConfirmDialog_Text {
            get {
                return ResourceManager.GetString("ConfirmDialog_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proceed.
        /// </summary>
        public static string ConfirmDialog_Tile {
            get {
                return ResourceManager.GetString("ConfirmDialog_Tile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello World7.
        /// </summary>
        public static string Home_Test {
            get {
                return ResourceManager.GetString("Home_Test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cineflex.
        /// </summary>
        public static string Home_Title {
            get {
                return ResourceManager.GetString("Home_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Film.
        /// </summary>
        public static string Navbar_Item1 {
            get {
                return ResourceManager.GetString("Navbar_Item1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cineflex.
        /// </summary>
        public static string Navbar_Title {
            get {
                return ResourceManager.GetString("Navbar_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date and time.
        /// </summary>
        public static string Reserve_Date {
            get {
                return ResourceManager.GetString("Reserve_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have chosen for seat number {0}  .
        /// </summary>
        public static string Reserve_Notice {
            get {
                return ResourceManager.GetString("Reserve_Notice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room Number.
        /// </summary>
        public static string Reserve_RoomNumber {
            get {
                return ResourceManager.GetString("Reserve_RoomNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The  Seat.
        /// </summary>
        public static string Reserve_Seat {
            get {
                return ResourceManager.GetString("Reserve_Seat", resourceCulture);
            }
        }
    }
}
